version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: resume_matcher_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: @Sunilsaroj1008
    ports:
      - "5432:5432"
